name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@10.15.0 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: (Optional) allow build scripts for native deps
        run: pnpm config set allow-scripts true

      - name: Typecheck
        run: pnpm run --if-present typecheck

      - name: Lint
        run: pnpm run --if-present lint

      - name: Build
        run: pnpm run build